name: Mon Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Installe Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Installe Dépendance
      run: pip install -r requirement.txt

    - name : Execution de mon script python
      run: python script.py
